---
abstract: 'BerkeleyDB Cache Driver for CHI'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Class: '0'
  Test::More: '0'
  Test::Most: '0'
  lib: '0'
  parent: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CHI-Driver-BerkeleyDB
provides:
  CHI::Driver::BerkeleyDB:
    file: lib/CHI/Driver/BerkeleyDB.pm
    version: '0.04'
requires:
  BerkeleyDB: '0.30'
  CHI::Driver: '0'
  File::Path: '0'
  Moose: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/mschout/perl-chi-driver-bdb/issues
  homepage: https://github.com/mschout/perl-chi-driver-bdb
  repository: https://github.com/mschout/perl-chi-driver-bdb.git
version: '0.04'
x_serialization_backend: 'YAML::Tiny version 1.70'
